#1
Name=c("Alex","lilly","Maark","Oliver")
Age=c(25,31,23,52)
Height=c(177,163,190,179)
weight=c(57,69,83,75)
Sex=as.factor(c("F","F","M","M"))
df=data.frame(row.names=Name,Age,Height,weight,Sex)
levels(df$Sex)
df
levels(df$Sex)<-c("M","F")
df
#2
working<-c("Yes","No","No","Yes")
df2=data.frame(row.names=Name,working)
df2
df<-cbind(df,df2)
dim(df)
str(df)
#3
class(state.center)
data.state=as.data.frame(state.center)
#4
a=rnorm(10)
b=letters[4:13]
c=c("yes","no","no","no","no","yes","no","yes","yes","no")
df3=data.frame(a,b,c)
df3[with(df3, order(a)), ]
#5
matrix.data<-matrix(1:10,nrow=5,ncol=2)
df<-as.data.frame(matrix.data)
colnames(df)<-paste("variable_",1:ncol(df))
rownames(df)<-paste("id_",1:nrow(df))
df
#6
class(VADeaths)
df<-data.frame(VADeaths)
df$Total<-rowSums(df)
df<-df[,c(5,1,2,3,4)]
df
#7
class(state.x77)
df2<-data.frame(state.x77)
nrow(df2[df2$Income<4300,])
row.names(df2[which.max(df2$Income),])
#8
df3<-data.frame(swiss[c(1,2,3,10,11,12,13),c("Examination","Education","Infant.Mortality")])
df3$Infant.Mortality[4]<-NA
Total<-colSums(df3,na.rm = TRUE)
df4<-rbind(df3,Total)
rownames(df4)=c(rownames(df3),"Total")
df4